APT::FTPArchive::Release::Origin "Phoenix-Go";
APT::FTPArchive::Release::Label "Phoenix-Go";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "ios";
APT::FTPArchive::Release::Architectures "iphoneos-arm64e";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Phoenix-Go repo";
